Repository CMU-17313Q/nodebb-f24-gaurdiansofthegit, pull requests merged in 2024-09, with the labels that each got.

#30 Refactoring code to reduce cognitive complexity in src/middleware/user.js
  dump.rdb
  src/middleware/user.js
Labels: enhancement

#29 Refactor code in src/controllers/mods.js to reduce cognitive complexity
  src/controllers/mods.js
Labels: enhancement

#32 Refactor code to reduce cognitive complexity from 16 to 15 in src/user/settings.js
  src/user/settings.js
Labels: enhancement

#31 Refactoring code in install.js and increasing coverage and console log in flag.js
  src/flags.js
  src/install.js
  test/flags.js
Labels: enhancement

#40 Back-end Navigation Links on Header
  .gitignore
  dump.rdb
  node_modules/nodebb-theme-harmony/templates/partials/header/brand.tpl
  src/messaging/rooms.js
  src/views/admin/manage/categories.tpl
Labels: back-end

#46 Made the navigation header dynamic - changes based on specific url's
  node_modules/nodebb-theme-harmony/templates/partials/header/brand.tpl
Labels: back-end, front-end
