Repository CMU-17313Q/nodebb-f24-gaurdiansofthegit, pull requests merged in 2024-10, with the labels that each got.

#53 Added "src/bad-words.txt" for Filtering Inappropriate Language
  public/bad-words.txt
  src/bad-words.txt
Labels: enhancement, good first issue, Low effort

#54 Anonymity for post replies and database schema for posts
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  src/controllers/mods.js
  src/flags.js
  src/messaging/rooms.js
  src/middleware/user.js
  src/posts/create.js
  src/topics/posts.js
Labels: Medium effort, back-end

#57 Private Posts: Added a checkbox button to the front-end for posting privately
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl
Labels: Medium effort, front-end

#63 Private Posts: Added private flag for posts back-end
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl
  src/posts/create.js
  src/posts/index.js
  src/posts/topics.js
  src/topics/posts.js
  test/api.js
Labels: High effort, back-end

#65 Private Posts: Automated tests for private posting
  UserGuide.md
  test/privateposts.js
Labels: Low effort, testing

#62 Added a function "loadBadWords()" and bad word detection under src/posts/create.js that loads the txt file
  src/posts/create.js
Labels: enhancement, Medium effort, back-end

#70 Created Automated test cases for the dynamic links on header
  node_modules/nodebb-theme-harmony/templates/partials/header/brand.tpl
  test/categories.js
Labels: Medium effort, testing
